name: Build RuqaiyaPro 107

on:
  push:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Java 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Setup Android SDK
        uses: android-actions/setup-android@v3

      - name: Build APK Debug
        run: |
          echo "sdk.dir=$ANDROID_HOME" > local.properties
          cat local.properties
          chmod +x gradlew
          ./gradlew assembleDebug --stacktrace -x lint -x test --no-daemon

      - name: Upload APK
        if: success()
        uses: actions/upload-artifact@v4
        with:
          name: RuqaiyaPro-107-FINAL
          path: app/build/outputs/apk/debug/app-debug.apk
